In [2]:
import os
import numpy as np
from matplotlib import pyplot
from scipy import optimize
from scipy.io import loadmat
import utils
%matplotlib inline

In [7]:
m = 10
k = 4
h_lay = 5
X = np.random.rand(m, h_lay)
y = np.random.randint(k, size = m)
theta1 = np.random.rand(h_lay, h_lay+1)/100
theta2 = np.random.rand(k, h_lay+1)/100
nn_params = np.concatenate([theta1.ravel(), theta2.ravel()])

In [8]:
def nnCostFunction(nn_params,
                   input_layer_size,
                   hidden_layer_size,
                   num_labels,
                   X, y, lambda_, dum1):

    # Reshape nn_params back into the parameters Theta1 and Theta2, the weight matrices
    # for our 2 layer neural network
    Theta1 = np.reshape(nn_params[:hidden_layer_size * (input_layer_size + 1)],
                        (hidden_layer_size, (input_layer_size + 1)))

    Theta2 = np.reshape(nn_params[(hidden_layer_size * (input_layer_size + 1)):],
                        (num_labels, (hidden_layer_size + 1)))

    # Setup some useful variables
    m = y.size
         
    # You need to return the following variables correctly 
    J = 0
    Theta1_grad = np.zeros(Theta1.shape)
    Theta2_grad = np.zeros(Theta2.shape)

    # ====================== YOUR CODE HERE ======================
    
    # Add ones to the X data matrix, and rename as A1
    X = np.concatenate([np.ones((m, 1)), X], axis=1)
    
    # Matrix of activation-unit outputs of the hidden layer:
    A_2 = utils.sigmoid(np.dot(X,Theta1.T))
    
    # Add column of "ones" for bias activation unit:
    A_2 = np.concatenate([np.ones((m, 1)), A_2], axis=1)
    
    # Matrix of output elements (h_theta(x)):
    h = utils.sigmoid(np.dot(A_2,Theta2.T))
    
    # Generate (m x K) matrix with training outputs where each element has been replaced with row vector
    # containing a "1" for the given class (e.g., if yi = 5 --> yi = [0,0,0,0,0,1,0,0,0,0] )
    ym = np.zeros((m,num_labels))
    
    for i in range(m):
        ym[i,y[i]] = 1
    
    # Compute cost function w/o regularization:
    #J = -1/m*np.sum(ym*np.log(h)+(1-ym)*np.log(1-h))
    
    # For regularization, need to sum over all elements of Theta1 and Theta2, but first need to zero-out 
    # the first column of each matrix to make sure bias elems are not included:

    print("before reg assignment \n")
    print("Theta1 = ", Theta1)
    print("Theta2 = ", Theta2)
    
    theta1_reg = Theta1
    theta2_reg = Theta2
    
    print("Theta1_reg = ", theta1_reg)
    print("Theta2_reg = ", theta2_reg)
    
    theta1_reg[:,0] = 0
    theta2_reg[:,0] = 0
    
    print("after reg assignment \n") 
    print("Theta1 = ", Theta1)
    print("Theta2 = ", Theta2)
    print("Theta1_reg = ", theta1_reg)
    print("Theta2_reg = ", theta2_reg)    
    
    print("dum1 = ", dum1)
    dum1_reg = dum1
    dum1_reg[0] = 3
    print("dum1 = ", dum1)
    print("dum1_reg = ", dum1_reg)
    
    # Compute cost function w/i regularization:
    J = -1/m*np.sum(ym*np.log(h)+(1-ym)*np.log(1-h)) + lambda_/(2*m)*(np.sum(theta1_reg**2)+np.sum(theta2_reg**2))
    
    # ================================================================
    # Unroll gradients
    # grad = np.concatenate([Theta1_grad.ravel(order=order), Theta2_grad.ravel(order=order)])
    grad = np.concatenate([Theta1_grad.ravel(), Theta2_grad.ravel()])

    return J, grad

In [9]:
lambda_ = 0
dummy1 = np.array([1,1,1,1,1])
J, _ = nnCostFunction(nn_params, h_lay, h_lay,
                   k, X, y, lambda_, dummy1)
print('Cost at parameters (loaded from ex4weights): %.6f ' % J)

before reg assignment 

Theta1 =  [[2.63644854e-03 9.91861082e-03 5.75850828e-03 2.37080694e-03
  7.15622880e-03 1.69522981e-03]
 [9.66580786e-03 9.41047067e-03 3.85854443e-03 2.48210435e-03
  5.08657049e-03 4.02367398e-03]
 [1.63895518e-03 3.02917963e-03 1.37900623e-03 8.16683873e-03
  2.91286253e-03 9.48589245e-03]
 [1.56258952e-03 2.36316774e-03 4.00641243e-05 3.06055236e-03
  9.84799100e-03 6.27681894e-03]
 [1.94046499e-03 5.28869740e-03 9.48367343e-04 6.85711721e-03
  8.14913652e-03 9.88360156e-04]]
Theta2 =  [[0.00080291 0.00520612 0.0078579  0.00713746 0.0064728  0.00861299]
 [0.00676835 0.00033225 0.00940566 0.00890329 0.00088102 0.00883949]
 [0.00050711 0.0082209  0.00667289 0.00882214 0.0017566  0.00668947]
 [0.00781549 0.00123627 0.001719   0.00276625 0.00056899 0.00208521]]
Theta1_reg =  [[2.63644854e-03 9.91861082e-03 5.75850828e-03 2.37080694e-03
  7.15622880e-03 1.69522981e-03]
 [9.66580786e-03 9.41047067e-03 3.85854443e-03 2.48210435e-03
  5.08657049e-03 4.02367398e-03]

In [ ]:
Theta1_reg

In [3]:
x = np.array([1,1,1,1,1])
y = x.copy()
y[0] = 0
print(x)
print(y)

[1 1 1 1 1]
[0 1 1 1 1]


In [4]:
x = np.array([1,1,1,1,1])
y = x
y[0] = 0
print(x)
print(y)

[0 1 1 1 1]
[0 1 1 1 1]


In [7]:
a = [1,1,1,1,1]
b = a
b[0] = 0
print(a)
print(b)

[0, 1, 1, 1, 1]
[0, 1, 1, 1, 1]


In [14]:
X

array([[0.15558562, 0.61372935, 0.52779738, 0.50162874, 0.35387695],
       [0.3102538 , 0.1774894 , 0.66288124, 0.49251496, 0.5029875 ],
       [0.55815247, 0.02155552, 0.52282552, 0.13845692, 0.6224235 ],
       [0.44712756, 0.89189773, 0.05142846, 0.79364447, 0.4670996 ],
       [0.39035733, 0.71314361, 0.97980052, 0.80840111, 0.57740809],
       [0.19767468, 0.34441336, 0.06307796, 0.9085284 , 0.10218188],
       [0.08547756, 0.56989856, 0.20632091, 0.22838358, 0.11249418],
       [0.82502688, 0.58514292, 0.09542148, 0.02753516, 0.3203712 ],
       [0.91949664, 0.84480103, 0.54328002, 0.05211455, 0.91103071],
       [0.04958964, 0.08765251, 0.70843611, 0.58321932, 0.0493383 ]])

In [15]:
X = X[:,1:]
X

array([[0.61372935, 0.52779738, 0.50162874, 0.35387695],
       [0.1774894 , 0.66288124, 0.49251496, 0.5029875 ],
       [0.02155552, 0.52282552, 0.13845692, 0.6224235 ],
       [0.89189773, 0.05142846, 0.79364447, 0.4670996 ],
       [0.71314361, 0.97980052, 0.80840111, 0.57740809],
       [0.34441336, 0.06307796, 0.9085284 , 0.10218188],
       [0.56989856, 0.20632091, 0.22838358, 0.11249418],
       [0.58514292, 0.09542148, 0.02753516, 0.3203712 ],
       [0.84480103, 0.54328002, 0.05211455, 0.91103071],
       [0.08765251, 0.70843611, 0.58321932, 0.0493383 ]])