In [52]:
import os
import numpy as np
from matplotlib import pyplot as plt

In [25]:
# features matrix
X = np.array([[1,1,1,1],[2104, 1416, 1534, 852],[5, 3, 3, 2],[1, 2, 2, 1],[45, 40, 30, 36]]).T
print(X)

[[   1 2104    5    1   45]
 [   1 1416    3    2   40]
 [   1 1534    3    2   30]
 [   1  852    2    1   36]]


In [26]:
# Parameters vector
theta = np.array([[80,0.1,0.01,3,-2]]).T
print(theta)

[[ 8.e+01]
 [ 1.e-01]
 [ 1.e-02]
 [ 3.e+00]
 [-2.e+00]]


In [28]:
# output vector
y = np.array([[460, 232, 315, 178]]).T
print(y)

[[460]
 [232]
 [315]
 [178]]


In [43]:
# number of examples
m = y.size
print(m)

4


In [49]:
J = 1/(2*m)*np.sum((np.dot(X,theta)-y)**2)
J

12250.424087499998

In [50]:
alpha = 1
theta_up = theta - alpha/m*np.transpose(np.dot(np.transpose(np.dot(X,theta)-y),X))
print(theta_up)

[[2.19567500e+02]
 [2.34222615e+05]
 [5.26542500e+02]
 [1.97552500e+02]
 [5.48068250e+03]]


In [59]:
data = np.loadtxt(os.path.join('../Exercise1/Data' ,'ex1data2.txt'), delimiter=',')
X = data[:, :2]
y = data[:, 2]
m = y.size

In [90]:
X[:,1]

array([3., 3., 3., 2., 4., 4., 3., 3., 3., 3., 4., 3., 3., 5., 3., 4., 2.,
       3., 4., 4., 3., 2., 3., 4., 3., 3., 3., 3., 3., 3., 2., 1., 4., 3.,
       4., 3., 3., 4., 4., 4., 2., 3., 4., 3., 2., 4., 3.])

In [87]:
mu = np.zeros(X.shape[1])
mu = X.mean(0)
mu

array([2000.68085106,    3.17021277])

In [85]:
np.average(X[:,0])

2000.6808510638298

In [81]:
sigma = np.zeros(X.shape[1])
sigma = X.std(0)
sigma

array([7.86202619e+02, 7.52842809e-01])

In [83]:
X_dummy = X[0:10,0:10]
X_dummy

array([[2.104e+03, 3.000e+00],
       [1.600e+03, 3.000e+00],
       [2.400e+03, 3.000e+00],
       [1.416e+03, 2.000e+00],
       [3.000e+03, 4.000e+00],
       [1.985e+03, 4.000e+00],
       [1.534e+03, 3.000e+00],
       [1.427e+03, 3.000e+00],
       [1.380e+03, 3.000e+00],
       [1.494e+03, 3.000e+00]])

In [91]:
(X_dummy - mu)

array([[ 1.03319149e+02, -1.70212766e-01],
       [-4.00680851e+02, -1.70212766e-01],
       [ 3.99319149e+02, -1.70212766e-01],
       [-5.84680851e+02, -1.17021277e+00],
       [ 9.99319149e+02,  8.29787234e-01],
       [-1.56808511e+01,  8.29787234e-01],
       [-4.66680851e+02, -1.70212766e-01],
       [-5.73680851e+02, -1.70212766e-01],
       [-6.20680851e+02, -1.70212766e-01],
       [-5.06680851e+02, -1.70212766e-01]])

In [88]:
(2.104e+03 - 2000.68085106)

103.3191489400001

In [96]:
data = np.loadtxt(os.path.join('../Exercise1/Data' ,'ex1data2.txt'), delimiter=',')
X = data[:, :2]
y = data[:, 2]
m = y.size
X = np.concatenate([np.ones((m, 1)), X], axis=1)

In [103]:
X

array([[1.000e+00, 2.104e+03, 3.000e+00],
       [1.000e+00, 1.600e+03, 3.000e+00],
       [1.000e+00, 2.400e+03, 3.000e+00],
       [1.000e+00, 1.416e+03, 2.000e+00],
       [1.000e+00, 3.000e+03, 4.000e+00],
       [1.000e+00, 1.985e+03, 4.000e+00],
       [1.000e+00, 1.534e+03, 3.000e+00],
       [1.000e+00, 1.427e+03, 3.000e+00],
       [1.000e+00, 1.380e+03, 3.000e+00],
       [1.000e+00, 1.494e+03, 3.000e+00],
       [1.000e+00, 1.940e+03, 4.000e+00],
       [1.000e+00, 2.000e+03, 3.000e+00],
       [1.000e+00, 1.890e+03, 3.000e+00],
       [1.000e+00, 4.478e+03, 5.000e+00],
       [1.000e+00, 1.268e+03, 3.000e+00],
       [1.000e+00, 2.300e+03, 4.000e+00],
       [1.000e+00, 1.320e+03, 2.000e+00],
       [1.000e+00, 1.236e+03, 3.000e+00],
       [1.000e+00, 2.609e+03, 4.000e+00],
       [1.000e+00, 3.031e+03, 4.000e+00],
       [1.000e+00, 1.767e+03, 3.000e+00],
       [1.000e+00, 1.888e+03, 2.000e+00],
       [1.000e+00, 1.604e+03, 3.000e+00],
       [1.000e+00, 1.962e+03, 4.00

In [101]:
theta = np.dot(np.dot(np.linalg.inv(np.dot(X.T, X)),X.T),y)
the

In [100]:
89597.9095428 + 139.21067402*1650 + -8738.01911233*3

293081.46433880995

In [105]:
x_house = np.array([3, 1650, 1])
np.dot(x_house,theta)

489753.3216451407

In [108]:
# Load data


# print out some data points
print('{:>8s}{:>8s}{:>10s}'.format('X[:,0]', 'X[:, 1]', 'y'))
print('-'*26)
for i in range(20):
    print('{:8.0f}{:8.0f}{:10.0f}'.format(X[i, 0], X[i, 1], y[i]))

  X[:,0] X[:, 1]         y
--------------------------
       1    2104    399900
       1    1600    329900
       1    2400    369000
       1    1416    232000
       1    3000    539900
       1    1985    299900
       1    1534    314900
       1    1427    198999
       1    1380    212000
       1    1494    242500
       1    1940    239999
       1    2000    347000
       1    1890    329999
       1    4478    699900
       1    1268    259900
       1    2300    449900
       1    1320    299900
       1    1236    199900
       1    2609    499998
       1    3031    599000


In [106]:
x

NameError: name 'x' is not defined