In [2]:
import numpy as np

In [34]:
X2 = np.array([[11,4,10],[44,5,6],[7,83,33],[22,44,33],[27,86,55],[1,3,4],[53,34,32]])
X3 = np.array([[11,2,4],[3,5,7],[7,83,33],[23,34,34],[0,86,0],[1,5,4],[5,34,3]])
T2 = np.array([[31,12,15],[22,2,4],[41,15,18],[42,3,5]])
T1 = np.array([[1],[2],[3]])
mu = np.array([1,1,1])

In [40]:
np.dot(X2,X2)

array([[  237,   564,   739,   748,  1191,    63,  1039],
       [  564,  1997,   921,  1386,  1948,    83,  2694],
       [  739,   921,  8027,  4895,  9142,   388,  4249],
       [  748,  1386,  4895,  3509,  6193,   286,  3718],
       [ 1191,  1948,  9142,  6193, 11150,   505,  6115],
       [   63,    83,   388,   286,   505,    26,   283],
       [ 1039,  2694,  4249,  3718,  6115,   283,  4989]])

In [38]:
np.dot(X2,T1)

array([[ 49],
       [ 72],
       [272],
       [209],
       [364],
       [ 19],
       [217]])

In [13]:
(np.where(X2>10,1,0) == 1) & (np.where(X3>10,1,0) == 1)

array([[ True, False, False],
       [False, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True, False],
       [False, False, False],
       [False,  True, False]])

In [4]:
X2

array([[11,  4, 10],
       [44,  5,  6],
       [ 7, 83, 33],
       [22, 44, 33],
       [27, 86, 55],
       [ 1,  3,  4],
       [53, 34, 32]])

In [7]:
np.where(X2>10,1,0)


array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [0, 0, 0],
       [1, 1, 1]])

In [5]:
np.mean(X2,axis=0)

array([23.57142857, 37.        , 24.71428571])

In [6]:
mu

array([1, 1, 1])

In [7]:
X2-mu

array([[10,  3,  9],
       [43,  4,  5],
       [ 6, 82, 32],
       [21, 43, 32],
       [26, 85, 54],
       [ 0,  2,  3],
       [52, 33, 31]])

In [8]:
mu-X2

array([[-10,  -3,  -9],
       [-43,  -4,  -5],
       [ -6, -82, -32],
       [-21, -43, -32],
       [-26, -85, -54],
       [  0,  -2,  -3],
       [-52, -33, -31]])

In [9]:
X2'

array([[11,  4, 10],
       [44,  5,  6],
       [ 7, 83, 33],
       [22, 44, 33],
       [27, 86, 55],
       [ 1,  3,  4],
       [53, 34, 32]])

In [13]:
n = np.array([0,0,2,1,1,2,0])

In [28]:
for k in range(3):
    ck = n == k
    print(X2[ck,:])
    print(np.mean(X2[ck,:],axis=0))

[[11  4 10]
 [44  5  6]
 [53 34 32]]
[36.         14.33333333 16.        ]
[[22 44 33]
 [27 86 55]]
[24.5 65.  44. ]
[[ 7 83 33]
 [ 1  3  4]]
[ 4.  43.  18.5]


In [34]:
np.random.permutation(X2.shape[0])

array([3, 6, 2, 4, 0, 1, 5])

In [23]:
(11.0+44.0+53.0)/3.0

36.0

In [26]:
11+4+10

25

In [17]:
a = np.random.randint(2,size=10)
b = np.random.randint(2,size=10)
print(a)
print(b)

[0 0 1 1 1 0 0 0 1 0]
[1 1 1 1 1 1 1 0 1 1]


In [21]:
X = (a==1)&(b==1).astype(int)
print(X)

[0 0 1 1 1 0 0 0 1 0]


In [22]:
np.sum(X)

4

In [30]:
a = np.dot(np.array([1,2,3,4]),np.array([[1,2],[3,4],[5,6],[7,8]]))
np.dot(a,np.array([[1,2],[3,4],[5,6],[7,8]]).T)

array([170, 390, 610, 830])

In [27]:
k = np.array([[1,2],[3,4],[5,6],[7,8]])
k[0,:]

array([1, 2])