In [1]:
import numpy as np
import sympy as sp
from qiskit_textbook.tools import array_to_latex

In [2]:
x00, x01, x02, x10, x11, x12, x20, x21, x22, x30, x31, x32 = sp.symbols('x00, x01, x02, x10, x11, x12, x20, x21, x22, x30, x31, x32')
t00, t01, t02, t10, t11, t12 = sp.symbols('t00, t01, t02, t10, t11, t12')

In [3]:
X = sp.Matrix([[x00, x01, x02],[x10, x11, x12],[x20, x21, x22],[x30, x31, x32]])
T = sp.Matrix([[t00, t01, t02],[t10, t11, t12]])

In [4]:
X

Matrix([
[x00, x01, x02],
[x10, x11, x12],
[x20, x21, x22],
[x30, x31, x32]])

In [5]:
X.T

Matrix([
[x00, x10, x20, x30],
[x01, x11, x21, x31],
[x02, x12, x22, x32]])

In [6]:
T

Matrix([
[t00, t01, t02],
[t10, t11, t12]])

In [7]:
X*T.T

Matrix([
[t00*x00 + t01*x01 + t02*x02, t10*x00 + t11*x01 + t12*x02],
[t00*x10 + t01*x11 + t02*x12, t10*x10 + t11*x11 + t12*x12],
[t00*x20 + t01*x21 + t02*x22, t10*x20 + t11*x21 + t12*x22],
[t00*x30 + t01*x31 + t02*x32, t10*x30 + t11*x31 + t12*x32]])

In [10]:
X.T*X

Matrix([
[    x00**2 + x10**2 + x20**2 + x30**2, x00*x01 + x10*x11 + x20*x21 + x30*x31, x00*x02 + x10*x12 + x20*x22 + x30*x32],
[x00*x01 + x10*x11 + x20*x21 + x30*x31,     x01**2 + x11**2 + x21**2 + x31**2, x01*x02 + x11*x12 + x21*x22 + x31*x32],
[x00*x02 + x10*x12 + x20*x22 + x30*x32, x01*x02 + x11*x12 + x21*x22 + x31*x32,     x02**2 + x12**2 + x22**2 + x32**2]])

In [11]:
X*X.T

Matrix([
[   x00**2 + x01**2 + x02**2, x00*x10 + x01*x11 + x02*x12, x00*x20 + x01*x21 + x02*x22, x00*x30 + x01*x31 + x02*x32],
[x00*x10 + x01*x11 + x02*x12,    x10**2 + x11**2 + x12**2, x10*x20 + x11*x21 + x12*x22, x10*x30 + x11*x31 + x12*x32],
[x00*x20 + x01*x21 + x02*x22, x10*x20 + x11*x21 + x12*x22,    x20**2 + x21**2 + x22**2, x20*x30 + x21*x31 + x22*x32],
[x00*x30 + x01*x31 + x02*x32, x10*x30 + x11*x31 + x12*x32, x20*x30 + x21*x31 + x22*x32,    x30**2 + x31**2 + x32**2]])

In [18]:
X2 = np.array([[11,4,10],[44,5,6],[7,83,33],[22,44,33],[27,86,55],[1,3,4],[53,34,32]])
T2 = np.array([[31,12,15],[22,2,4],[41,15,18],[42,3,5]])

In [19]:
XT2 = np.dot(X2,T2.T)
print(XT2)

[[ 539  290  691  524]
 [1514 1002 1987 1893]
 [1708  452 2126  708]
 [1705  704 2156 1221]
 [2694  986 3387 1667]
 [ 127   44  158   71]
 [2531 1362 3259 2488]]


In [20]:
np.argmax(XT2, axis = 1)

array([2, 2, 2, 2, 2, 2, 2])

In [22]:
XT2.ravel()

array([ 539,  290,  691,  524, 1514, 1002, 1987, 1893, 1708,  452, 2126,
        708, 1705,  704, 2156, 1221, 2694,  986, 3387, 1667,  127,   44,
        158,   71, 2531, 1362, 3259, 2488])

In [28]:
a = np.sum(XT2,axis=1)
np.sum(a)

37994

In [24]:
539+290+691+524

2044

In [51]:
x = np.array([[1],[1],[4],[3],[2],[0],[0],[2],[4],[3]])
x

array([[1],
       [1],
       [4],
       [3],
       [2],
       [0],
       [0],
       [2],
       [4],
       [3]])

In [33]:
one = np.array([1])
rep = one()

array([1])

In [72]:
x[:,0]

array([1, 1, 4, 3, 2, 0, 0, 2, 4, 3])

In [73]:
m = 10
n = 5
ym = np.zeros((m,n))
ym

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [74]:
ym[:,x[,0]] = 1
ym

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
for i in range(m):
    ym[i,x[i,0]] = 1
    
ym

array([[0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.]])

In [7]:
t10, t20, t30, t11, t21, t31, t12, t22, t32, t13, t23, t33  = sp.symbols('t10, t20, t30, t11, t21, t31, t12, t22, t32, t13, t23, t33')

In [8]:
THET = sp.Matrix([[t10, t20, t30],[t11, t21, t31],[t12, t22, t32],[t13, t23, t33]])
THET

Matrix([
[t10, t20, t30],
[t11, t21, t31],
[t12, t22, t32],
[t13, t23, t33]])

In [12]:
d1, d2, d3 = sp.symbols('d1, d2, d3')
d11, d12, d13 = sp.symbols('d11, d12, d13')
d21, d22, d23 = sp.symbols('d21, d22, d23')
d31, d32, d33 = sp.symbols('d31, d32, d33')
d41, d42, d43 = sp.symbols('d41, d42, d43')
d51, d52, d53 = sp.symbols('d51, d52, d53')

In [10]:
delt = sp.Matrix([[d1],[d2],[d3]])
delt

Matrix([
[d1],
[d2],
[d3]])

In [11]:
THET*delt

Matrix([
[d1*t10 + d2*t20 + d3*t30],
[d1*t11 + d2*t21 + d3*t31],
[d1*t12 + d2*t22 + d3*t32],
[d1*t13 + d2*t23 + d3*t33]])

In [13]:
delt2 = sp.Matrix([[d11, d12, d13],[d21, d22, d23],[d31, d32, d33],[d41, d42, d43],[d51, d52, d53]])
delt2

Matrix([
[d11, d12, d13],
[d21, d22, d23],
[d31, d32, d33],
[d41, d42, d43],
[d51, d52, d53]])

In [15]:
delt2*THET.T

Matrix([
[d11*t10 + d12*t20 + d13*t30, d11*t11 + d12*t21 + d13*t31, d11*t12 + d12*t22 + d13*t32, d11*t13 + d12*t23 + d13*t33],
[d21*t10 + d22*t20 + d23*t30, d21*t11 + d22*t21 + d23*t31, d21*t12 + d22*t22 + d23*t32, d21*t13 + d22*t23 + d23*t33],
[d31*t10 + d32*t20 + d33*t30, d31*t11 + d32*t21 + d33*t31, d31*t12 + d32*t22 + d33*t32, d31*t13 + d32*t23 + d33*t33],
[d41*t10 + d42*t20 + d43*t30, d41*t11 + d42*t21 + d43*t31, d41*t12 + d42*t22 + d43*t32, d41*t13 + d42*t23 + d43*t33],
[d51*t10 + d52*t20 + d53*t30, d51*t11 + d52*t21 + d53*t31, d51*t12 + d52*t22 + d53*t32, d51*t13 + d52*t23 + d53*t33]])

In [25]:
a0, a1, a2, a3 = sp.symbols('a0, a1, a2, a3')
a10, a11, a12, a13 = sp.symbols('a10, a11, a12, a13')
a20, a21, a22, a23 = sp.symbols('a20, a21, a22, a23')
a30, a31, a32, a33 = sp.symbols('a30, a31, a32, a33')
a40, a41, a42, a43 = sp.symbols('a40, a41, a42, a43')
a50, a51, a52, a53 = sp.symbols('a50, a51, a52, a53')

In [26]:
A2 = sp.Matrix([[a10, a11, a12, a13],[a20, a21, a22, a23],[a30, a31, a32, a33],[a40, a41, a42, a43],[a50, a51, a52, a53]])
A2

Matrix([
[a10, a11, a12, a13],
[a20, a21, a22, a23],
[a30, a31, a32, a33],
[a40, a41, a42, a43],
[a50, a51, a52, a53]])

In [29]:
a = sp.Matrix([[a0],[a1],[a2],[a3]])
a

Matrix([
[a0],
[a1],
[a2],
[a3]])

In [34]:
delt2.T*A2

Matrix([
[a10*d11 + a20*d21 + a30*d31 + a40*d41 + a50*d51, a11*d11 + a21*d21 + a31*d31 + a41*d41 + a51*d51, a12*d11 + a22*d21 + a32*d31 + a42*d41 + a52*d51, a13*d11 + a23*d21 + a33*d31 + a43*d41 + a53*d51],
[a10*d12 + a20*d22 + a30*d32 + a40*d42 + a50*d52, a11*d12 + a21*d22 + a31*d32 + a41*d42 + a51*d52, a12*d12 + a22*d22 + a32*d32 + a42*d42 + a52*d52, a13*d12 + a23*d22 + a33*d32 + a43*d42 + a53*d52],
[a10*d13 + a20*d23 + a30*d33 + a40*d43 + a50*d53, a11*d13 + a21*d23 + a31*d33 + a41*d43 + a51*d53, a12*d13 + a22*d23 + a32*d33 + a42*d43 + a52*d53, a13*d13 + a23*d23 + a33*d33 + a43*d43 + a53*d53]])

In [30]:
delt*a.T

Matrix([
[a0*d1, a1*d1, a2*d1, a3*d1],
[a0*d2, a1*d2, a2*d2, a3*d2],
[a0*d3, a1*d3, a2*d3, a3*d3]])