In [1]:
import numpy as np

In [4]:
X = np.array([[1],[4],[7]])
X

array([[1],
       [4],
       [7]])

In [6]:
np.power(X,2)

array([[ 1],
       [16],
       [49]])

In [33]:
p = 3
X_poly = np.zeros((X.shape[0], p))

for i in range(1,p+1):
    X_poly[:,i-1] = X[:,0]**i
    

print(X**p, "\n")
print(X_poly)

[[  1]
 [ 64]
 [343]] 

[[  1.   1.   1.]
 [  4.  16.  64.]
 [  7.  49. 343.]]
