In [73]:
import os
import numpy as np
from matplotlib import pyplot
import utils

In [39]:
M = np.array([[1,2],[3,4]])
print(M)

[[1 2]
 [3 4]]


In [11]:
1/(1+np.exp(-M))

array([[0.73105858, 0.88079708],
       [0.95257413, 0.98201379]])

In [33]:
np.log(1/(1+np.exp(-3)))

-0.04858735157374191

In [19]:
X = np.array([[1,2,3],[4,5,6]])
np.shape(X)

(2, 3)

In [29]:
t = np.array([[1],[4],[8]])

In [28]:
np.dot(t.T,X.T)

array([[33, 72]])

In [30]:
np.log(np.exp(2))

2.0

In [44]:
data = np.loadtxt(os.path.join('../../Exercise2/Data', 'ex2data1.txt'), delimiter=',')
X, y = data[:, 0:2], data[:, 2]

In [45]:
pos = y == 1
neg = y == 0

In [46]:
pos

array([False, False, False,  True,  True, False,  True,  True,  True,
        True, False, False,  True,  True, False,  True,  True, False,
        True,  True, False,  True, False, False,  True,  True,  True,
       False, False, False,  True,  True, False,  True, False, False,
       False,  True, False, False,  True, False,  True, False, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True,  True,  True, False, False,
       False, False, False,  True, False,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True])

In [58]:
theta = np.array([[-25.161], [0.206], [0.201]])

In [62]:
np.dot(theta.T,theta)

array([[633.158758]])

In [63]:
np.sum(theta**2)

633.158758

In [74]:
# Load Data
# The first two columns contains the X values and the third column
# contains the label (y).
data = np.loadtxt(os.path.join('../../Exercise2/Data', 'ex2data2.txt'), delimiter=',')
X = data[:, :2]
y = data[:, 2]
X = utils.mapFeature(X[:, 0], X[:, 1])

In [78]:
theta

array([[-25.161],
       [  0.206],
       [  0.201]])

In [86]:
theta0 = np.vstack(([0],theta[1:]))
theta0

array([[0.   ],
       [0.206],
       [0.201]])